#!/bin/bash
#PBS -A GEO019
#PBS -N ConstrainedBubble
#PBS -j oe
#PBS -l walltime=2:00:00,nodes=1
#PBS -l gres=widow2%widow3

#cd /tmp/work/$USER
date

cd $PBS_O_WORKDIR

#echo "PBS_O_WORKDIR: `echo $PBS_O_WORKDIR`"
source $MODULESHOME/init/bash
module swap cray-mpich2 cray-mpich2/5.6.3
export LD_LIBRARY_PATH=${CRAY_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}
export MPICH_RDMA_ENABLED_CUDA=1
aprun -n 1 -N 1 ~/LBPM-WIA/bin/Color-WIA-CBUB
