#!/bin/bash

cmake -D CMAKE_C_COMPILER:PATH=/opt/arden/openmpi/3.1.2/bin/mpicc          \
    -D CMAKE_CXX_COMPILER:PATH=/opt/arden/openmpi/3.1.2/bin/mpicxx        \
    -D CMAKE_C_FLAGS="-O3 -fPIC"         \
    -D CMAKE_CXX_FLAGS="-O3 -fPIC "      \
    -D CMAKE_CXX_STANDARD=14    \
    -D MPIEXEC=mpirun  \
    -D CMAKE_BUILD_PARALLEL_LEVEL=4      \
    -D USE_EXT_MPI_FOR_SERIAL_TESTS:BOOL=TRUE \
    -D CMAKE_BUILD_TYPE:STRING=Release     \
    -D CUDA_FLAGS="-arch sm_35"          \
    -D CUDA_HOST_COMPILER="/usr/bin/gcc" \
    -D USE_HDF5=1 \
    -D HDF5_DIRECTORY="/opt/arden/hdf5/1.8.12" \
    -D HDF5_LIB="/opt/arden/hdf5/1.8.12/lib/libhdf5.a"\
    -D USE_DOXYGEN=true \
    -D USE_SILO=false \
    -D USE_CUDA=0                        \
    -D USE_TIMER=0 \
    ~/Programs/LBPM

