# Macro to find and configure timer
MACRO( CONFIGURE_TIMER )
    SET( NULL_TIMER_DIR "${LBPM_INSTALL_DIR}/include" )
    # Determine if we want to use the timer utility
    CHECK_ENABLE_FLAG( USE_TIMER 1 )
    IF ( USE_TIMER )
        # Check if we specified the timer directory
        EXECUTE_PROCESS( COMMAND ${CMAKE_COMMAND} -E remove -f "${NULL_TIMER_DIR}/ProfilerApp.h" )
        IF ( TIMER_DIRECTORY )
            VERIFY_PATH ( ${TIMER_DIRECTORY} )
            VERIFY_PATH ( ${TIMER_DIRECTORY}/include )
            VERIFY_PATH ( ${TIMER_DIRECTORY}/lib )
            SET( TIMER_INCLUDE ${TIMER_DIRECTORY}/include )
            FIND_LIBRARY( TIMER_LIBS  NAMES timerutility  PATHS ${TIMER_DIRECTORY}/lib  NO_DEFAULT_PATH )
            SET( TIMER_CXXFLAGS "-DUSE_TIMER -I${TIMER_DIRECTORY}/include" )
            SET( TIMER_LDFLAGS -L${TIMER_DIRECTORY}/lib )
            SET( TIMER_LDLIBS -ltimerutility )
        ELSE()
            MESSAGE( FATAL_ERROR "Default search for TIMER is not yet supported.  Use -D TIMER_DIRECTORY=" )
        ENDIF()
        SET(CMAKE_INSTALL_RPATH ${CMAKE_INSTALL_RPATH} "${TIMER_DIRECTORY}/lib" )
        INCLUDE_DIRECTORIES( ${TIMER_INCLUDE} )
        ADD_DEFINITIONS( "-D USE_TIMER" )
        MESSAGE( "Using timer utility" )
        MESSAGE( "  TIMER_LIBRARIES = ${TIMER_LIBS}" )
    ELSE()
        FILE(WRITE  "${NULL_TIMER_DIR}/ProfilerApp.h" "#define PROFILE_START(...)       do {} while(0)\n" )
        FILE(APPEND "${NULL_TIMER_DIR}/ProfilerApp.h" "#define PROFILE_STOP(...)        do {} while(0)\n" )
        FILE(APPEND "${NULL_TIMER_DIR}/ProfilerApp.h" "#define PROFILE_START2(...)      do {} while(0)\n" )
        FILE(APPEND "${NULL_TIMER_DIR}/ProfilerApp.h" "#define PROFILE_STOP2(...)       do {} while(0)\n" )
        FILE(APPEND "${NULL_TIMER_DIR}/ProfilerApp.h" "#define PROFILE_SCOPED(...)      do {} while(0)\n" )
        FILE(APPEND "${NULL_TIMER_DIR}/ProfilerApp.h" "#define PROFILE_SYNCRONIZE()     do {} while(0)\n" )
        FILE(APPEND "${NULL_TIMER_DIR}/ProfilerApp.h" "#define PROFILE_SAVE(...)        do {} while(0)\n" )
        FILE(APPEND "${NULL_TIMER_DIR}/ProfilerApp.h" "#define PROFILE_STORE_TRACE(X)   do {} while(0)\n" )
        FILE(APPEND "${NULL_TIMER_DIR}/ProfilerApp.h" "#define PROFILE_ENABLE(...)      do {} while(0)\n" )
        FILE(APPEND "${NULL_TIMER_DIR}/ProfilerApp.h" "#define PROFILE_DISABLE()        do {} while(0)\n" )
        FILE(APPEND "${NULL_TIMER_DIR}/ProfilerApp.h" "#define PROFILE_ENABLE_TRACE()   do {} while(0)\n" )
        FILE(APPEND "${NULL_TIMER_DIR}/ProfilerApp.h" "#define PROFILE_DISABLE_TRACE()  do {} while(0)\n" )
        FILE(APPEND "${NULL_TIMER_DIR}/ProfilerApp.h" "#define PROFILE_ENABLE_MEMORY()  do {} while(0)\n" )
        FILE(APPEND "${NULL_TIMER_DIR}/ProfilerApp.h" "#define PROFILE_DISABLE_MEMORY() do {} while(0)\n" )
        MESSAGE( "Disabling timer utility" )
    ENDIF()
ENDMACRO()



